# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import communication_pb2 as communication__pb2


class CommunicatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushModel = channel.unary_unary(
                '/gossip.Communicator/PushModel',
                request_serializer=communication__pb2.Model.SerializeToString,
                response_deserializer=communication__pb2.Reply.FromString,
                )


class CommunicatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def PushModel(self, request, context):
        """Call RPC Server's SendModel to send the model to RPC Server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PushModel,
                    request_deserializer=communication__pb2.Model.FromString,
                    response_serializer=communication__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gossip.Communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communicator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def PushModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Communicator/PushModel',
            communication__pb2.Model.SerializeToString,
            communication__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
